### ISSUE TITLE
Дошка на Гіті

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#1]
Створити на гітхабі до свого проекту дошку з
стовпчиками - Planned, InProgress,
ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.

**Comment by sophiayaropud** [comment]
завдання виконано: створено на гітхабі до нашого проекту дошку з
стовпчиками - Planned, InProgress, ReadyForReview, Done.
