### ISSUE TITLE
Rewrite project to 3-tier architecture

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#102]
Rewrite your windows to 3 tier architecture. After add "check" to the corresponding checkbox.
- [x] @MykhailoSiomachok  "Settings" window
- [x] @anastasiiaktsb  "ProfileAndStatistics" window
- [x] @OlhaDanyliuk  "Main" window
- [x] @sophiayaropud  "Login" and "Registations" windows

Add comments with screenshots of new .cs files
Do not close until all things on the list are checked.

**Comment by MykhailoSiomachok** [comment]
Settings window addidtional files for 3-tier architecture
![2020-11-13 13_00_32-DrinkWater - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/62886029/99065560-3e063c80-25b0-11eb-90f5-f6c8428b47a4.png)

**Comment by OlhaDanyliuk** [comment]
![Знімок екрана (716)](https://user-images.githubusercontent.com/48630214/99802611-a8832380-2b40-11eb-8cb6-eb2a9fdec0d4.png)
Main Window addidtional files for 3-tier architecture

**Comment by anastasiiaktsb** [comment]
![image](https://user-images.githubusercontent.com/45684119/100448105-792d6300-30ba-11eb-84dc-19ea4082d0b5.png)
done
