### ISSUE TITLE
Add logging of unhandled exceptions

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#119]
Application.DispatcherUnhandledException Event.

**Comment by MykhailoSiomachok** [comment]
Done
![2020-12-04 11_36_24-Example log_ Блокнот](https://user-images.githubusercontent.com/62886029/101147580-3e30af80-3625-11eb-8067-f94da3f4ee05.png)

**Comment by anastasiiaktsb** [comment]
done
