### ISSUE TITLE
[UML] Розробити схему бази даних

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#14]
Розробити схему бази даних з таблицями у вигляді відповідної UML діаграми. 
Для кожної таблиці вказати дані, які там будуть зберігатися, типи, а також залежності між таблицями.

**Comment by OlhaDanyliuk** [comment]
![UML-schema database](https://user-images.githubusercontent.com/48630214/95378738-03442100-08ed-11eb-947d-f0959aa42bfb.png)

**Comment by MykhailoSiomachok** [comment]
Все в порядку
