### ISSUE TITLE
[App] Створити методи

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#24]
Створити методи для заповнення бази даних тестовими даними.
**Зауваження:**
Не закривайте завдання допоки усі checkbox не будуть відмічені(допоки всі не заллють методи в свої гілки):

- [x] метод @anastasiiaktsb 
- [x] метод @sophiayaropud 
- [x] метод @OlhaDanyliuk 

Також окрім заповнення tasklist`а напишіть відповідні коментарі і створіть pull request

**Comment by sophiayaropud** [comment]
Я додала файл з методами на свою гілку.

**Comment by anastasiiaktsb** [comment]
Додано файл з методами та їх тестами.

**Comment by OlhaDanyliuk** [comment]
Залила функції і тести на свою гілку

**Comment by MykhailoSiomachok** [comment]
Всі все зробили
