### ISSUE TITLE
Use-case діаграма

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#3]
По визначених для вашого проекту ролях
намалювати usecase діаграми

**Comment by MykhailoSiomachok** [comment]
Оля і Софія створили use-case діаграму
![photo_2020-09-18_14-09-27](https://user-images.githubusercontent.com/62886029/93591211-9659fd00-f9b8-11ea-9af1-55fab1e14fc8.jpg)

**Comment by MykhailoSiomachok** [comment]
Розроблена use-case діаграма
![photo_2020-09-18_14-45-23](https://user-images.githubusercontent.com/62886029/93594030-c6f06580-f9bd-11ea-9e02-6dd236ce5bfc.jpg)

**Comment by OlhaDanyliuk** [comment]
![Blank diagram](https://user-images.githubusercontent.com/48630214/93883724-9fb1d500-fcea-11ea-97f2-7c9b04a36661.png)
Кінцева діаграма. Для юзера додали кейс "edit data" і додали адміна з такими ж кейсами як у юзера + кейс з можливістю переглядати дані про юзерів в базі даних
