### ISSUE TITLE
Доцільна назва

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#4]
Вивчити, як доцільно назвати нашу "програму": застосунком, додатком, аплікацією чи програмою

**Comment by MykhailoSiomachok** [comment]
Посилання на правильну назву:
https://onlinecorrector.com.ua/uk/%D0%B7%D0%B0%D1%81%D1%82%D0%BE%D1%81%D1%83%D0%BD%D0%BE%D0%BA-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B0/
https://slovotvir.org.ua/words/aplikatsiia
https://uk.wikipedia.org/wiki/%D0%97%D0%B0%D1%81%D1%82%D0%BE%D1%81%D1%83%D0%BD%D0%BE%D0%BA

**Comment by anastasiiaktsb** [comment]
Михайло дослідив доцільність слова "програма"
