### ISSUE TITLE
Admin use-case

### ISSUE THREAD

**Issue by MykhailoSiomachok** [Programming-Engineering-Pmi-33/Drink_water#6]
Створити admin use-case діаграму

**Comment by OlhaDanyliuk** [comment]
![Blank diagram](https://user-images.githubusercontent.com/48630214/93883272-0682be80-fcea-11ea-8f50-65154ee974be.png)
Оскільки більшість use case адміна співпадають з кейсами юзера, доцільно буде об'єднати ці діаграми таким чином
