### ISSUE TITLE
Збільшити відстань від лейблів і додати bold

### ISSUE THREAD

**Issue by OlhaDanyliuk** [Programming-Engineering-Pmi-33/Drink_water#96]

**Comment by MykhailoSiomachok** [comment]
Labels were formated
![2020-11-13 12_50_48-DrinkWater - Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/62886029/99064623-e0252500-25ae-11eb-8449-726e7d17a02f.png)

**Comment by anastasiiaktsb** [comment]
done
